### ISSUE TITLE
Workbench and ship repairs are not saved on game save.

### ISSUE THREAD

**Issue by razieli** [oribro/Spacehack#18]
We need to store the cells that contain workbenches (and possibly other future interact-able objects) so we could save and load them.
We also need to save the state of the ship.

**Comment by razieli** [comment]
This issue is now generalized to "big objects" that are not stored on game save.
The ship fire state also doesn't load.

**Comment by oribro** [comment]
I noticed that the big objects are actually loaded nicely.
